name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  enforce-no-mocks-policy:
    name: Enforce No-Mocks Policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for prohibited terms
        run: |
          git diff --cached origin/main...HEAD | tee changes.diff
          disallow='lorem ipsum|placeholder|TODO: mock|fake_key_|example\.com/api'
          if grep -Ei "$disallow" changes.diff; then
            echo "❌ No-Mocks policy violation detected."
            exit 1
          fi
          echo "✅ No policy violations found"

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm test -- --coverage --silent

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
